spring.application.name=notification-service
server.port=8083

#Mail Properties
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=967f4c16f2cb86
spring.mail.password=28cc83de1b3f75

## Observability
#management.endpoints.web.exposure.include=health, info, metrics, prometheus
#management.metrics.distribution.percentiles-histogram.http.server.requests=true
#management.observations.key-values.application=notification-service
#management.tracing.sampling.probability=1.0


#SQS
spring.cloud.aws.region.static=us-east-1

# Credentials (use dummy for LocalStack)
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# SQS endpoint for LocalStack
spring.cloud.aws.sqs.endpoint=http://localhost:4566

queue.name=ORDER_CREATED_QUEUE

