services:
  product-mongodb:
    image: mongo:7.0.5
    container_name: product-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: product-service
    volumes:
      - ./.data/mongo:/data/db
    networks:
      - backend-net

  mongodb-exporter:
    image: percona/mongodb_exporter:0.44.0
    container_name: mongodb-exporter
    ports:
      - "9216:9216"
    command:
      - "--mongodb.uri=mongodb://root:password@product-mongodb:27017/admin"
      - "--collect-all"
      - "--compatible-mode"
    depends_on:
      - product-mongodb
    networks:
      - backend-net

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8080:8080"
    volumes:
      - ./product-service:/app
    depends_on:
      - product-mongodb
    networks:
      - backend-net

  order-mysql:
    image: mysql:8.3.0
    container_name: order-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./.data/mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8081:8081"
    volumes:
      - ./order-service:/app
    depends_on:
      - order-mysql
      - localstack
    networks:
      - backend-net

  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "8083:8083"
    volumes:
      - ./notification-service:/app
    depends_on:
      - localstack
    networks:
      - backend-net

  localstack:
    container_name: localstack
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      # LocalStack configuration: https://docs.localstack.cloud/references/configuration/
      - DEBUG=${DEBUG:-0}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - backend-net

  loki:
    image: grafana/loki:main
    container_name: loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    networks:
      - backend-net

  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - backend-net

  grafana:
      image: grafana/grafana:10.1.0
      container_name: grafana
      volumes:
        - ./docker/grafana:/etc/grafana/provisioning/datasources:ro
      environment:
        - GF_AUTH_ANONYMOUS_ENABLED=true
        - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
        - GF_AUTH_DISABLE_LOGIN_FORM=true
      ports:
        - "3000:3000"
      networks:
        - backend-net


  db-mysql:
    image: mysql:8.3.0
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - ./.data/mysql_db:/var/lib/mysql
      - ./docker/mysql/init_2.sql:/docker-entrypoint-initdb.d/init_2.sql

networks:
  backend-net: