<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.sfazim.e_commerce</groupId>
    <artifactId>spring-boot-performace-lab</artifactId>

    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Spring Boot Performance Lab</name>
    <description>Spring boot microservice E-commerce</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <modules>
        <module>product-service</module>
        <module>order-service</module>
        <module>notification-service</module>
        <module>shipping-service</module>
    </modules>
</project>
