spring.application.name=shipping-service
server.port=8084


## Observability
#management.endpoints.web.exposure.include=health, info, metrics, prometheus
#management.metrics.distribution.percentiles-histogram.http.server.requests=true
#management.observations.key-values.application=notification-service
#management.tracing.sampling.probability=1.0


#SQS
spring.cloud.aws.region.static=us-east-1

# Credentials (use dummy for LocalStack)
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# SQS endpoint for LocalStack
spring.cloud.aws.sqs.endpoint=http://localhost:4566

queue.name=ORDER_SHIPPED_QUEUE

