#Application
spring.application.name=order-service

#Database
spring.datasource.url=jdbc:mysql://localhost:3306/order_service
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
server.port=8081

#OpenAPI swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs


#SQS
spring.cloud.aws.region.static=us-east-1

# Credentials (use dummy for LocalStack)
spring.cloud.aws.credentials.access-key=test
spring.cloud.aws.credentials.secret-key=test

# SQS endpoint for LocalStack
spring.cloud.aws.sqs.endpoint=http://localhost:4566
#SNS endpoint for LocalStack
spring.cloud.aws.sns.endpoint=http://localhost:4566

queue.names=ORDER_CREATED_QUEUE,ORDER_SHIPPED_QUEUE
sns.topic.name=ORDER_TOPIC