#Application
spring.application.name=db_performance

#Database
spring.datasource.url=jdbc:mysql://localhost:3307/e_commerce
spring.datasource.username=root
spring.datasource.password=mysql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
server.port=8088

#db
# Automatically create database tables based on JPA entities.
# 'create' drops and recreates tables on each app start (good for dev, not prod).
# Use 'update' to apply changes without dropping existing data.
spring.jpa.hibernate.ddl-auto=create

# Show the generated SQL statements in the console/logs (helpful for debugging).
spring.jpa.show-sql=true

# Format the SQL output to be more readable with proper indentation.
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.stat=DEBUG
## Enable SQL query logging in console
logging.level.org.hibernate.SQL=DEBUG





## Show SQL queries
#spring.jpa.show-sql=true
#
## Format SQL queries
#spring.jpa.properties.hibernate.format_sql=true
#
## Enable SQL query logging in console
#logging.level.org.hibernate.SQL=DEBUG
#
## Enable SQL parameter binding logging (very useful!)
#logging.level.org.hibernate.type.descriptor.sql=TRACE
#
## Show HikariCP logs
#logging.level.com.zaxxer.hikari=DEBUG
#
## Show Spring Data JPA logs
#logging.level.org.springframework.orm.jpa=DEBUG
#logging.level.org.springframework.transaction=DEBUG

#
## Show SQL and format it
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.highlight_sql=true
#spring.jpa.properties.hibernate.use_sql_comments=true
#
## Show Hibernate config details
#spring.jpa.properties.hibernate.show_configuration=true
#
## Logging levels
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.com.zaxxer.hikari=DEBUG

#OpenAPI swagger
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Observability
# Expose specific actuator endpoints via HTTP (health, info, metrics, and Prometheus)
management.endpoints.web.exposure.include=health, info, metrics, prometheus

# Enable histogram buckets for HTTP server request metrics (required for latency percentiles)
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Attach a custom key-value (tag) to all observations and metrics (e.g., "application=product-service")
management.observations.key-values.application=product-service

# Set tracing sampling rate to 100% (i.e., trace every request, useful in dev or testing)
management.tracing.sampling.probability=1.0

# Enable Tomcat's MBean registry for collecting detailed JVM and server stats
server.tomcat.mbeanregistry.enabled=true